# Generated by Django 3.0.7 on 2021-07-19 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='sampleposts.User'),
        ),
    ]
